### ISSUE TITLE
smil_packed_info.pth not found!

### ISSUE THREAD

**Issue by JincanDeng** [ZZWENG/Diffusion_HPC#1]
Hi, thanks for your amazing work! I want to try the demo by running api.py, but meeting the error says:
`FileNotFoundError: [Errno 2] No such file or directory: '/root/.romp/smil_packed_info.pth'`.
Any advice for this?

**Comment by ZZWENG** [comment]
Hi, you can find this file in ROMP/BEV's project page: https://github.com/Arthur151/ROMP/tree/master/simple_romp
