### ISSUE TITLE
No file or directory

### ISSUE THREAD

**Issue by xz-123-new** [ZZWENG/Diffusion_HPC#2]
Thanks for your great work! To generate files smil_packed_info.pth which is needed for api.py, I download the SMPL_python_v.1.1.0 according to the instruction in simple_romp, but no file called SMPL_NEUTRAL.pkl or SMPL_NEUTRAL.pth is available, would you please inform me where could i locate it or download it, thanks!

**Comment by ZZWENG** [comment]
Hi these files can be found in "~/.romp" once you install simple_romp. `https://github.com/Arthur151/ROMP/tree/4eebd3647f57d291d26423e51f0d514ff7197cb3/simple_romp`
The files in `~/.romp` are:
`
BEV.pth  ROMP.pkl  smil_packed_info.pth  SMPLA_FEMALE.pth  SMPLA_MALE.pth  SMPLA_NEUTRAL.pth  SMPL_FEMALE.pth  SMPL_MALE.pth  SMPL_NEUTRAL.pth
`
Hope that helps.

**Comment by xz-123-new** [comment]
Thanks for your help! Now I can successfuuly acquire files BEV.pth  ROMP.pkl  smil_packed_info.pth  SMPLA_NEUTRAL.pth  SMPL_NEUTRAL.pth in /.romp folder, but in your api.py, a file named smpla_packed_info.pth is further needed, and seems like the download link https://github.com/Arthur151/ROMP/releases/download/V2.0/smpla_packed_info.pth is broken, would you please tell me the exact instruction to generate this file or where i could download it, thanks!

**Comment by xz-123-new** [comment]
The exact location need smpla_packed_info.pth is in class SMPLA_parser(nn.Module), it requires a smpla_path to construct  self.smpl_model = SMPL(smpla_path, model_type='smpla'), and the smpla_path exactly need this file, but i don know how to generate it or how to skip this process, thanks for your help!

**Comment by ZZWENG** [comment]
perhaps check ~/.bev  ?

Sent from my iPhone

On Dec 12, 2023, at 16:37, xz ***@***.***> wrote:

﻿

The exact location need smpla_packed_info.pth is in class SMPLA_parser(nn.Module), it requires a smpla_path to construct self.smpl_model = SMPL(smpla_path, model_type='smpla'), and the smpla_path exactly need this file, but i don know how to generate it or how to skip this process, thanks for your help!

**Comment by xz-123-new** [comment]
Sadly there is no folder ~/.bev available. If it is not troublesome, would you please provide this smpla_packed_info.pth through a new download link? I would really appreciate it.

**Comment by ZZWENG** [comment]
Hi, sorry for the confusion. Please download here: https://drive.google.com/file/d/1QejCf9lAlV-kHyHEHmQV34fgbbR1rF9H/view?usp=drive_link

**Comment by xz-123-new** [comment]
Thanks for your efforts! Now i can run api.py, but i encounter another problem confusing me, the depth_image generated from HMR process is sized 512x1024, which mismatch the origin image 512x512. And no matter i choose the left or right part(to crop it to 512x512) of depth image as depth guidance, weird results are generated as follow
<img width="881" alt="875741b98f6b91e59e775d661caa62b" src="https://github.com/ZZWENG/Diffusion_HPC/assets/100124503/c83162ed-3b46-47e7-b45d-25ed267e4963"> which part did i misfollow, is it the problem of HMR process, and is it expected to acquire a depth image actually 512x512? Really thanks for your help and sorry for my continual disturbance.

**Comment by gofixyourself** [comment]
@xz-123-new Hello!

How you solved this error, if it occured in your case? I mean, when you run api.py
`pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"`

**Comment by gofixyourself** [comment]
I have the same problem with missmatched shapes for depth_map and non_person_mask.

**Comment by Arka-h** [comment]
I can't seem to find or generate `smpl_packed_info.pth` from the simple_romp code.
Would not having `smpl_packed_info.pth` affect the generation? or can the error `HTTP Error 404: Not Found
Failure in downloading the SMPL model, please download it by youself from https://github.com/Arthur151/ROMP/releases/download/V2.0/smpl_packed_info.pth, and put it to ...` be safely ignored, as it generates images anyway?
